### ISSUE TITLE
Local Network access

### ISSUE THREAD

**Issue by mikemand** [laravel/valet#440] opened 2017-09-21 22:36 UTC
I have Valet installed on my iMac, and I'm hoping to be able to access it on the local network from my iPad. I only need to run one site from it (I'm making a label printer "bridge" since Zebra doesn't care about SSL). When I go to the iMac's IP address in my browser, I get the basic `Valet - Not Found` page. Is there some way to tell Valet to serve whatever site as the "default" so I can access it from the iPad? Thanks in advance for any help.

**Comment by joshmanders** [comment] 2017-09-21 23:30
Relevant: https://github.com/laravel/valet/pull/439

**Comment by mikemand** [comment] 2017-09-21 23:40
Thank you for that. I didn't even check PRs, just issues. I did not see any issues that match my problem, but I may have missed them...

I'll check that PR and give it a test. 👍

**Comment by drbyte** [comment] 2017-09-22 00:18
Ya, it's almost the perfect use-case for it.

**Comment by adamwathan** [comment] 2017-09-22 11:33
You can also use `valet share`.

**Comment by mikemand** [comment] 2017-09-22 17:30
`valet share` does not work in this case, because I'm having to rely on things "Just Working™️". If someone restarts the Mac, then the server needs to just automatically come back up. Unless you have some way for `valet share` to automatically run on reboot, and get the same ngrok URL...

**Comment by wimurk** [comment] 2017-09-26 13:30
+1 need this

**Comment by bloggervista** [comment] 2018-01-24 08:58
so i cannot share using my local area ip to share using valet? I need to connect to internet? I guess this needs to be fixed :)

**Comment by drbyte** [comment] 2018-01-24 13:58
Use #439 for that.

**Comment by bloggervista** [comment] 2018-01-24 15:33
@drbyte  you mean we change directly on file? But that is not merged and can get removed once we update isn't it?

**Closed** 2018-01-29 19:15 UTC

**Comment by xmarkclx** [comment] 2019-12-21 22:02
Hello there.
I found out a way to enable Local Network Access in latest Valet.

Edit `$HOME/.config/valet/config.json`

add a default after paths
Example:
```
{
  "paths": [
    "/Users/myusername/.config/valet/Sites"
  ],
  "default": "/Users/myusername/.config/valet/Sites/atlas",
  "tld": "test"
}
```

Edit `/usr/local/etc/nginx/valet/valet.conf`

Change `listen 127.0.0.1:80 default_server;` to the below
```
    listen 80 default_server;
```

**Comment by mkotsovoulou** [comment] 2020-01-14 13:15
> Hello there.
> I found out a way to enable Local Network Access in latest Valet.
> 
> Edit `$HOME/.config/valet/config.json`
> 
> add a default entry.
> 
> Example:
> 
> ```json
> {
>   "paths": [
>     "/Users/myusername/.config/valet/Sites"
>   ],
>   "default": "/Users/myusername/.config/valet/Sites/atlas",
>   "tld": "test"
> }
> ```
> 
> Edit `/usr/local/etc/nginx/valet/valet.conf`
> 
> Change `listen 127.0.0.1:80 default_server;` to the below
> 
> ```
>     listen 80 default_server;
> ```
> 
> Try it out using your ip on your own browser.
> If it works, it should work on any other browser in your network.

I have done all of the above steps but I can not access the site using my IP/blog.test
only from blog.test

So local network access does not work...
Id there anything else I can do?

**Comment by shirshak55** [comment] 2020-01-14 13:49
@mkotsovoulou  is ur ip port forwarded? can u access using localhost/blog.test?

**Comment by iskrisis** [comment] 2020-01-16 14:46
@mkotsovoulou don't forget to restart nginx. or do ```valet restart``` to be sure.

Is there some smart way to access all websites instead of just the one in "default"? It would be really nice if there was ```valet default``` that would change that config value. But i guess simple script will do.

**Comment by murrutia** [comment] 2020-01-29 16:07
The problem is that Valet checks for the hostname from the `$_SERVER['HTTP_HOST']` value, and in this case it's the IP address, so not a valid hostname.

I added this bit of code in the file `$HOME/.composer/vendor/laravel/valet/server.php` after the loading of `$valetConfig` :
```php
$valetConfig = json_decode(
    file_get_contents(VALET_HOME_PATH.'/config.json'), true
);

/**
 * If the HTTP_HOST is an IP address, check the start of the REQUEST_URI for a
 * valid hostname, extract and use it as the effective HTTP_HOST in place
 * of the IP. It enables the use of Valet in a local network.
 */
if (preg_match('/^([0-9]+\.){3}[0-9]+$/', $_SERVER['HTTP_HOST'])) {
    $uri = ltrim($_SERVER['REQUEST_URI'], '/');

    if (preg_match('/^[-.0-9a-zA-Z]+\.'. $valetConfig['tld'] .'/', $uri, $matches)) {
        $host = $matches[0];
        $_SERVER['HTTP_HOST'] = $host;
        $_SERVER['REQUEST_URI'] = str_replace($host, '', $uri);
    }
}
```

It should work immediately if you've already removed `127.0.0.1` from the `nginx` config as said in the previous comments.

**Comment by asumaran** [comment] 2022-08-18 21:48
@murrutia how's your solution is not included on Valet! It works with your code.
