### ISSUE TITLE
wordpress not working after valet 2.0 update

### ISSUE THREAD

**Issue by msonowal** [laravel/valet#256] opened 2016-12-13 08:54 UTC
Previously all the sites including **laravel** and **wordpress** projects are working fine on version 1, then I have freshly installed valet 2.0 as prior to release and when I try to access/open my **laravel** sites its working fine but **wordpress** is unable to work, when I try to access a **wordpress** site it redirects me to
`https://wordpress.dev/Users/username/.composer/vendor/laravel/valet/wp-admin/setup-config.php`
I think there is missing drivers currently in .valet/Drivers folder only `SampleValetDriver.php` file is there may be this could be the cause

**Comment by aaemnnosttv** [comment] 2016-12-13 09:52
There's been quite a few other issues opened around WordPress and v2.

Try updating valet to dev-master and running the install again.

The drivers in `~/.valet/Drivers` are where you can add your own custom drivers. The WordPress driver is [bundled in the valet source](https://github.com/laravel/valet/blob/master/cli/drivers/WordPressValetDriver.php).

**Comment by adamwathan** [comment] 2016-12-13 13:22
This seems to only happen on brand new Wordpress sites before creating a `wp-config.php` file.

I've updated the Wordpress driver to check for the existence of `wp-config-sample.php` when trying to detect a Wordpress install so that the driver will also handle installations that haven't been configured yet.

Update to `dev-master` and see if that helps.

**Comment by jpmurray** [comment] 2016-12-13 14:02
@adamwathan just throwing my two cents on this, I updated this week to 2.0 and just opened a WP install I had to work on (who previously worked) and it throws a 500 error. I'll go update to dev-master to see if anything changes, but here, it doesn't seems confined to new installs.

**Comment by adamwathan** [comment] 2016-12-13 14:05
There was a bug with 2.0 that broke a lot of sites that relied on pages other than `index.php` which was mostly fixed in 2.0.1 and should be totally fixed in `dev-master`, so try updating and running `valet install` again to make sure you have the latest nginx configuration and see if that helps 👍

**Comment by jpmurray** [comment] 2016-12-13 14:06
Just updated to dev-master, ran valet install and it didn't helped.

I wanted to send the logs, but valet's `nginx-error.log` stays empty :\

**Comment by adamwathan** [comment] 2016-12-13 14:07
What error are you seeing, a 500 or a 502? If it's a 500, is there any information if you inspect the response in the network tab of dev tools?

Worst case scenario, is there any way you can share a project that reproduces the issue?

**Comment by jpmurray** [comment] 2016-12-13 14:10
<img width="329" alt="screen shot 2016-12-13 at 09 08 51" src="https://cloud.githubusercontent.com/assets/1550428/21143257/e62f7ef4-c113-11e6-8eaf-79bc82425ef7.png">

That's what I get. Trying the response tab gives me a big "failed to load response data" (in Chrome dev tools). To the extent of my knowledge, I really get nothing to help on the error, sadly!

**Comment by jpmurray** [comment] 2016-12-13 14:24
Welp, I went on and uninstalled/reinstalled valet on dev-master. The WordPress install gives the same error with nothing helpful to debug.

BUT I have another WordPress install (just the base thing, it was installe before) that works just fine. Only difference (apart from the one working fine being a vanilla install), is the faulty one is on 4.5 and the one working is at 4.5.4. But the one failing today was working just fine last week, so I don't think the theme/plugins could be causing trouble here, but I might be mistaken?

I could give you access to the repo, it's "private" because of no real good administrative reasons, but there is no state secret I can't show you.

**Comment by jpmurray** [comment] 2016-12-13 14:33
All right, false alert on my case, sorry guys. There _is_ a plugin that is throwing an error and caused the install not to load.

Now, why I didn't see any error, apart in WP's own debug log once activated is another thing I guess.

But yeah, sorry! `dev-master` makes WP works fine!

**Comment by adamwathan** [comment] 2016-12-13 15:27
Closing this, should be resolved with latest changes to master.

**Closed by adamwathan** 2016-12-13 15:27 UTC
