### ISSUE TITLE
Guzzle API calls failing or timing out at 30 seconds

### ISSUE THREAD

**Issue by securit** [laravel/valet#968] opened 2020-07-08 07:50 UTC
I am trying to connect to Shopify using  the following:

On production this works perfectly, but on Valet, it takes a very long time to respond and sometimes times out. I debugged the connection and the one thing that sticks out is on Production Guzzle/Curl reports back TCP_NODELAY set. Whereas on Valet that is not set.
 
I would expect that Valet should operate the same way as the production server which is on Forge.

## Steps to Reproduce
```
$response = Http::withOptions(['debug'=>true])->withHeaders(['Content-Type' =>'application/graphql', 'X-Shopify-Access-Token'=>'######'])->post('https://######.myshopify.com/admin/api/2020-07/graphql.json',['{ shop{ name } }']);
```

## Diagnosis
<details>
<summary>sw_vers</summary>
<pre>ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.11.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/greg/PhpStorm"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "squizlabs/php_codesniffer": "*",
        "phpunit/phpunit": "^6.0",
        "symfony/thanks": "^1.0",
        "laravel/valet": "^2.11",
        "laravel/installer": "^3.1",
        "hirak/prestissimo": "^0.3.10"
    },
    "require-dev": {
        "phploc/phploc": "*",
        "phpmetrics/phpmetrics": "^2.4"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/greg/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.squizlabs/php_codesniffer : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.7 => 1.10.8)
Composer version: 1.10.7
PHP version: 7.4.7
PHP binary path: /usr/local/Cellar/php/7.4.7/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/greg/.composer
    1/8:	https://repo.packagist.org/p/provider-latest$8b7d28180814e0024a17a9121499b375919f541597a6ba390560c26f9a5b4150.json
    2/8:	https://repo.packagist.org/p/provider-2020-01$84e5fd5c71f125f8ce0aba9aebf8ba673bbe56f47c44f4a42a0e6f5f84b4ee56.json
    3/8:	https://repo.packagist.org/p/provider-2017$558cb9d427f2cfb6fbf5317621c84545316f3b280040ed590079013f569dc347.json
    4/8:	https://repo.packagist.org/p/provider-2020-04$2369dcd611775a78c4a4114d4906a16d08649acd00f6e6c7541737b01a5f1bc8.json
    5/8:	https://repo.packagist.org/p/provider-2019-10$a6a8c26ce54ce223b2ce7b3310d397f0d6f340ca49b0844d95ecd5c69fa4e426.json
    6/8:	https://repo.packagist.org/p/provider-2016$6d0adb12923050af45aca1fca03f59ef1a99661327b8d485e1c9abced756111f.json
    7/8:	https://repo.packagist.org/p/provider-2018$f6ad08b1a8ed423d7e7ff74b055d934c731efd9a91fd0c64ef1cc2c8a86e55f3.json
    8/8:	https://repo.packagist.org/p/provider-2019$a5032f4d49268d8b686ebc02ba2931dda65bdaf0e52a3df7eea10bc420b8d911.json
    Finished: success: 8, skipped: 0, failure: 0, total: 8
guzzlehttp/guzzle                  6.5.5   ~ 7.0.1   Guzzle is a PHP HTTP client library
illuminate/container               v7.17.2 ! v7.19.0 The Illuminate Container package.
illuminate/contracts               v7.17.2 ! v7.19.0 The Illuminate Contracts package.
laravel/installer                  v3.1.0  ! v3.2.0  Laravel application installer.
myclabs/deep-copy                  1.9.5   ! 1.10.1  Create deep copies (clones) of your objects
nikic/php-parser                   v4.5.0  ! v4.6.0  A PHP parser written in PHP
phar-io/manifest                   1.0.1   ~ 2.0.1   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1   ~ 3.0.2   Library for handling version information and constraints
phploc/phploc                      5.0.0   ~ 6.0.2   A tool for quickly measuring the size of a PHP project.
phpmetrics/phpmetrics              v2.7.3  ! v2.7.4  Static analyzer tool for PHP : Coupling, Cyclomatic complexity, Maintainability Index, Halstead's metrics... and more !
phpspec/prophecy                   v1.10.3 ! 1.11.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          5.3.2   ~ 8.0.2   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5   ~ 3.0.3   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   ~ 2.0.2   Simple template engine.
phpunit/php-timer                  1.0.9   ~ 5.0.1   Utility class for timing
phpunit/php-token-stream           2.0.2   ~ 4.0.3   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.5.14  ~ 9.2.5   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       5.0.10  ~ 6.1.2   Mock Object library for PHPUnit
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
sebastian/code-unit-reverse-lookup 1.0.1   ~ 2.0.2   Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.3   ~ 4.0.3   Provides the functionality to compare PHP values for equality
sebastian/diff                     2.0.1   ~ 4.0.2   Diff implementation
sebastian/environment              3.1.0   ~ 5.1.2   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.2   ~ 4.0.2   Provides the functionality to export PHP variables for visualization
sebastian/finder-facade            1.2.3   ~ 2.0.0   FinderFacade is a convenience wrapper for Symfony's Finder component.
sebastian/global-state             2.0.0   ~ 4.0.0   Snapshotting of global state
sebastian/object-enumerator        3.0.3   ~ 4.0.2   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1   ~ 2.0.2   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0   ~ 4.0.2   Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0   ~ 3.0.2   Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1   ~ 3.0.1   Library that helps with managing the version number of Git-hosted PHP projects
symfony/console                    v4.4.10 ~ v5.1.2  Symfony Console Component
symfony/service-contracts          v2.1.2  ! v2.1.3  Generic abstractions related to writing services</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x    2 root  wheel    64  4 Jun 12:09 .
drwxr-xr-x  121 root  wheel  3872  7 Jul 21:46 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f455fe28a7a47b51af090b308e95535d6cf0a423
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: be1ba3b4ba9549afdaff7bd35f2649b9df04fd8a
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_131
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: 11.5</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name       Status  User Plist
dnsmasq    started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
nginx      started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php        started root /Library/LaunchDaemons/homebrew.mxcl.php.plist
postgresql started greg /Users/greg/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
redis      started greg /Users/greg/Library/LaunchAgents/homebrew.mxcl.redis.plist
unbound    stopped</pre>
</details>
<details>
<summary>brew list --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>curl-openssl 7.71.0
dnsmasq 2.81
nginx 1.19.0
openssl@1.1 1.1.1g
php 7.4.7</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>atomicparsley
curl-openssl
ffmpeg
freetds
gcc
gdal
groonga
hdf5
imagemagick
ios-webkit-debug-proxy
json-c
libvorbis
netcdf
nginx
node
openblas
poppler
postgis
proj
python
sfcgal
sqlite
x264</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.4.7 (cli) (built: Jun 12 2020 00:04:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php
/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         /usr/local/etc/php/7.4/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.4/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.4/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.0</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.71.0
Age => 6
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin19.5.0
SSL Version => OpenSSL/1.1.1g
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/greg/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.1 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.0 (25 files, 2.1MB) *
  Poured from bottle on 2020-06-08 at 16:08:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 28,052 (30 days), 100,004 (90 days), 404,284 (365 days)
install-on-request: 27,451 (30 days), 97,109 (90 days), 389,997 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 7.4.7 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/7.4.7 (519 files, 76.1MB) *
  Poured from bottle on 2020-06-16 at 07:54:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl-openssl, freetds, freetype, gettext, glib, gmp, icu4c, jpeg, libffi, libpng, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, sqlite, tidy-html5, unixodbc, webp
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.4/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 44,330 (30 days), 147,893 (90 days), 515,324 (365 days)
install-on-request: 42,772 (30 days), 140,026 (90 days), 480,211 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1g (8,059 files, 18MB)
  Poured from bottle on 2020-04-23 at 14:42:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Analytics
install: 590,453 (30 days), 2,275,312 (90 days), 6,264,340 (365 days)
install-on-request: 73,880 (30 days), 334,556 (90 days), 827,279 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/local/sbin/php-fpm
/usr/sbin/php-fpm
/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 7.4.7 (fpm-fcgi) (built: Jun 12 2020 00:04:22)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.4/php-fpm.conf --test</summary>
<pre>[08-Jul-2020 19:47:44] NOTICE: configuration file /usr/local/etc/php/7.4/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 greg  staff   719  4 Jun 12:51 homebrew.mxcl.postgresql.plist
-rw-r--r--   1 greg  staff   823  8 Jun 14:38 homebrew.mxcl.redis.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 28 Jun 18:55 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 29 Jun 12:52 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   628 28 Jun 18:56 homebrew.mxcl.php.plist</pre>
</details>

**Comment by drbyte** [comment] 2020-07-08 12:29
This reply doesn't directly address the Guzzle communication delays, as I'm unable to reproduce the problem locally.

Nevertheless, a few things in the Diagnostics that stand out suggest a few local software updates may be beneficial:

> cat ~/.composer/composer.json

You may want to review whether all these packages are still needed and referencing appropriate versions. Some of them are pegged to much older releases than what is current.

> composer global outdated

Running `composer global update` will update these packages to their latest version according to your global composer.json constraints.

> composer global diagnose

It is reporting that your version of composer is slightly older. Running `composer self-update` will update it.

> brew outdated

Running `brew upgrade` will update all these packages to their latest.
Of interest in your list, as Guzzle uses it often, is curl-openssl

**Comment by securit** [comment] 2020-07-09 04:35
I upgraded everything as suggested with the exception of GuzzleHTTP because the latest version I could go to was 6.5 due to other dependencies like Spark.  I'm still experiencing the same issues. I have determined that the amount of time it takes is bang on 30 seconds, so something somewhere is timing out before proceeding. Right now I am going to install homestead (cries) because I cannot seem to get this down to an acceptable level.

**Comment by drbyte** [comment] 2020-07-09 13:48
> I have determined that the amount of time it takes is bang on 30 seconds, so something somewhere is timing out before proceeding.

- Does Guzzle have the ability to log when timeouts occur? It'd be useful to know what it's running into, and whether it's doing only the one "expected" request or whether it's doing other things where the timeout is happening.
- It'd be helpful to know whether it's having a DNS lookup issue before hitting the actual endpoint, or whether it's silently croaking on a TLS/SSL validation step (outdated local cert authority db) which prevents it from ever actually hitting the endpoint.
- Does Guzzle fail only on hitting this shopify URL? Or does it fail at everything it tries? http or https only?
- In your Mac's system preferences, on the Network screen, is your DNS set to use 127.0.0.1 (where dnsmasq service is running) or is it something else? Perhaps guzzle is hitting the wrong resolver?
<img width="338" alt="Screen Shot 2020-07-09 at 9 46 10 AM" src="https://user-images.githubusercontent.com/404472/87047976-2ca7c080-c1c9-11ea-8c9c-fa6ee55c103c.png">

**Comment by securit** [comment] 2020-07-09 20:13
Thank you for all of your advice. I have gotten to the bottom of this issue.
Firstly there were some expired digital certificates in my keychain. I removed all of the expired certificates one by boring one - I say boring because it required me to re enter my system password for each and every one... my system password is very long
I ran a `openssl s_client -connect www.google.com:443` and got different results for google vs shopify. 
I checked the DNS settings and discovered I did not have a setting for 127.0.0.1. So I put that in after my two other DNS server settings (one points to my local router, the other to Google). There was no improvement. 
However, once I moved the 127.0.0.1 to the top of the list "Hey Presto!" :)
I would say that the google response was different because it was resolving google via the 8.8.8.8 DNS entry. 
It sounds like dnsmasq requires a 127.0.0.1 entry at the top of the list of DNS resolvers in order to function, is that correct? If so, then it may pay to add that to the documentation or ensure that when Valet is installed it checks the DNS resolvers order and ensure that the loopback exists and is the first entry in the list.

**Comment by drbyte** [comment] 2020-07-10 02:53
> ensure that when Valet is installed it checks the DNS resolvers order and ensures that the loopback exists and is the first entry in the list

That would be ideal, although there are some pros and cons. We've had some discussion about automating that in #775. If you wish to help us move that along please continue the discussion there!

Special thanks for the detailed explanation of the steps you followed to get to the solution. It's very helpful to have that complete context.

If this issue is resolved for you, please close it with the button below.

If you don't mind, would you consider editing the title to be slightly more reflective of the original symptom? 
eg: something akin to "Guzzle API calls failing or timing out at 30 seconds"

**Closed** 2020-07-10 02:54 UTC

**Comment by drbyte** [comment] 2020-07-10 03:03
> I put that in after my two other DNS server settings (one points to my local router, the other to Google)

FYI: You can put those into dnsmasq's config so that it intentionally does its fallback to them. This can speed things up slightly so that it directly hands it off to them instead of having to "fall through" as a failover.

Examples:
`/Users/ME/.config/valet/dnsmasq.d/dns-cloudflare1111-normal.conf`:
```
# Fallback servers to use if we can't resolve locally
# These are Cloudflare's public DNS:
# https://developers.cloudflare.com/1.1.1.1/
server=1.1.1.1
server=1.0.0.1
#server=2606:4700:4700::1111
#server=2606:4700:4700::1001
```
and/or
`/Users/ME/.config/valet/dnsmasq.d/dns-opendns-normal.conf`
```
# fallback servers to use if we can't resolve using our own rules
# these are for open-dns
server=208.67.220.222
server=208.67.220.220
```

`~/.config/valet/dnsmasq.d/*.conf` is the filename pattern
