### ISSUE TITLE
Laravel Valet hanging after upgrade

### ISSUE THREAD

**Issue by tillkruss** [laravel/valet#1245] opened 2022-04-18 20:53 UTC
Just upgraded from 2.x to 3.x and when running `valet install` afterwards it just hangs:

```
> valet install
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...

> valet install -vvv                                                                                                                                                                 
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
```

**Comment by NasirNobin** [comment] 2022-04-19 05:51
Duplicate of https://github.com/laravel/valet/issues/1224. This usually gets fixed after a reboot. 

Please try rebooting the device and run `valet install` again.

**Comment by driesvints** [comment] 2022-04-19 07:07
@tillkruss't please remember the issue template so we know which versions you're working with.

**Comment by driesvints** [comment] 2022-04-19 07:08
We're btw still debugging that issue as it's not always solved after a reboot. I'm still experiencing it.

**Closed by driesvints** 2022-04-19 07:07 UTC

**Comment by driesvints** [comment] 2022-04-19 10:45
Also see https://github.com/laravel/valet/issues/1226
