### ISSUE TITLE
valet not restarting linked php

### ISSUE THREAD

**Issue by aurawindsurfing** [laravel/valet#597] opened 2018-06-12 08:10 UTC
Hi,

Just came across a strange issue. I was trying to remove some modules from brew installed php 7.1 and I was doing 

![screen shot 2018-06-12 at 09 00 47](https://user-images.githubusercontent.com/14302496/41277930-770f8b20-6e20-11e8-8e2f-298dba5b0004.png)

 It was showing me that I'm restarting php.

Turns out that it does not restart php-fpm and only when I run: 

![screen shot 2018-06-12 at 09 01 12](https://user-images.githubusercontent.com/14302496/41277948-8118aec6-6e20-11e8-9a92-513823c2960e.png)

It actually restarted php-fpm and removed modules from loaded modules list.

Is that an expected behaviour or am I missing something here?

**Comment by Kyslik** [comment] 2018-06-12 10:17
OP on SO: https://stackoverflow.com/q/50811751/1564365

Yet again, copy the text, do not post images.

**Comment by Kyslik** [comment] 2018-06-12 10:30
As in SO I commented that valet uses `stop`/`start` vs `restart`: https://github.com/laravel/valet/blob/08932644cf3dbd167e509ee3946a266e3a71e235/cli/Valet/Brew.php#L142-L154

Already opened issue in homebrew-services by **[adamwathan](https://github.com/adamwathan)**  
 - https://github.com/Homebrew/homebrew-services/issues/102#issuecomment-277276088

I dug a bit deeper in brew-services repo:

restart command: https://github.com/Homebrew/homebrew-services/blob/master/cmd/brew-services.rb#L215-L228

run command: https://github.com/Homebrew/homebrew-services/blob/master/cmd/brew-services.rb#L252-L267

start command: https://github.com/Homebrew/homebrew-services/blob/master/cmd/brew-services.rb#L269-L296

stop command: https://github.com/Homebrew/homebrew-services/blob/master/cmd/brew-services.rb#L315-L348

**Comment by adamwathan** [comment] 2018-08-17 13:06
Closing this unless someone can provide a way to reliably reproduce it on a machine that isn't the OPs. 

Projects like Valet that are deeply integrated with someone's machine are unfortunately prone to a lot of issues due to interference from other unrelated services, configuration, etc. and although we try to help troubleshoot when we can, we don't consider issues like this actual "issues" with the project that can be resolved with a commit.

**Closed by adamwathan** 2018-08-17 13:06 UTC
