### ISSUE TITLE
how can I set the default site

### ISSUE THREAD

**Issue by yaochenfeng** [laravel/valet#472] opened 2017-11-23 07:53 UTC
I want the LAN user to access my IP and see the default site

**Comment by drbyte** [comment] 2017-11-23 14:15
Code for that is in an open PR: #439  You can implement that in your own PC now. It's working well for me.
Hopefully it will be merged soon.

**Comment by adamwathan** [comment] 2017-12-01 12:36
This is not currently supported and still unsure if we're going to merge that PR. Closing as it's not a bug.

**Closed by adamwathan** 2017-12-01 12:36 UTC
