### ISSUE TITLE
Drupal 7 index.php redirected you too many times

### ISSUE THREAD

**Issue by sajt** [laravel/valet#173] opened 2016-09-26 10:57 UTC
I am using valet 1.1.22 and it is working very well. Except if I try to use the 
`mydrupalsite.dev/index.php`
I get back 
`redirected you too many times`

That was worked in the previous version.

**Comment by danethomas** [comment] 2016-09-29 05:08
I seem to be running into a similar issue with craftCMS on 1.1.22 - only new to valet so I'm not sure if this was working previously.

**Comment by adamwathan** [comment] 2016-09-29 15:54
@sajt Having trouble replicating here, I get a "page not found" if I visit `index.php` directly:

![image](https://cloud.githubusercontent.com/assets/4323180/18961577/712b10b8-863b-11e6-83cc-476c644c1a05.png)

...and I get the main homepage it seems if I just hit `drupal.dev`:

![image](https://cloud.githubusercontent.com/assets/4323180/18961590/7c79c14e-863b-11e6-9f33-b17c407de90f.png)

Is there something else I need to do to replicate the issue?

@danethomas Craft seems to be working for me, what exactly are you doing where you are seeing the issue? What URL? I seem to be able to access the main public page and the admin dashboard without issues.

**Comment by adamwathan** [comment] 2016-10-13 23:23
Closing unless someone can help me reproduce.

**Closed by adamwathan** 2016-10-13 23:23 UTC

**Comment by sajt** [comment] 2016-10-14 12:36
Sorry it was solved, but I do not remember how was it.
