### ISSUE TITLE
Undefined index: extension

### ISSUE THREAD

**Issue by ClevonNoel** [laravel/valet#185] opened 2016-10-05 19:51 UTC
Constantly getting this error using the latest version of Valet

`<br />
<b>Notice</b>:  Undefined index: extension in <b>/Users/username/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php</b> on line <b>122</b><br />`

**Comment by drbyte** [comment] 2016-10-05 20:11
Are you trying to serve files that have no extension? http://php.net/manual/en/function.pathinfo.php
What sort of site are you encountering this with? Laravel? Other?

**Comment by ClevonNoel** [comment] 2016-10-06 12:32
I am running laravel application

**Comment by adamwathan** [comment] 2016-10-06 12:33
Can you create a small open source repo that replicates the issue so I can pull it down and try and troubleshoot?

**Comment by ClevonNoel** [comment] 2016-10-07 02:28
I just release that this error happen when there is a laravel router `/locations`

**Comment by KorvinSzanto** [comment] 2016-10-08 16:25
@ClevonNoel can you provide the route code that you use to replicate this issue?

**Comment by adamwathan** [comment] 2016-10-13 23:08
Cleaning up, closing this, will re-open if you can provide an update or a way to reproduce.

**Closed by adamwathan** 2016-10-13 23:08 UTC

**Comment by timgavin** [comment] 2016-10-14 12:35
This just started happening to me too, using Valet 1.1.22

```
<br />
<b>Notice</b>:  Undefined index: extension in <b>/Users/tim/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php</b> on line <b>122</b>
```

It's happening on an login route
```
<form class="form-horizontal" role="form" method="POST" action="{{ url('/login') }}">
```

And a GET route

```
<a href="{{ url('/home') }}">Home</a>
Route::get('home', 'PostController@home');
```

When logging in, the file downloads and I actually am logged in. When clicking on the `Home` link  the file downloads and I can't access the controller.

I decided to change the link from `{{ url('/home') }}` to `{{ url('/foo') }}` and it worked - no error. I also changed it to `{{ url('/logout') }}` and it worked too.

I then went into my routes file and commented out
```
// Route::get('home', 'PostController@home');
```

and the problem persisted, so it's not even making it to the routes file before downloading, so I'm assuming this is happening at the Valet level.

**Comment by adamwathan** [comment] 2016-10-14 12:36
Hey @timgavin, any chance you could create a small Laravel repo that recreates it so I can test it out and get to the bottom of it? Thanks!

**Comment by timgavin** [comment] 2016-10-14 12:42
@adamwathan Sure, if I can figure out how to recreate it. :P

**Comment by timgavin** [comment] 2016-10-14 19:42
OK, so my problem was because I stupidly had a directory named `home` in my `public` folder. *facepalm*

@ClevonNoel, could that be your problem too?

**Comment by ClevonNoel** [comment] 2016-10-17 14:48
@timgavin that  is correct. In my case i have a `locations` directory.
