### ISSUE TITLE
.valet folder is  created on /var/root/ place

### ISSUE THREAD

**Issue by MehmetNuri** [laravel/valet#405] opened 2017-07-20 12:26 UTC
My valet is create .valet folder on /var/root/ place

![screen shot 2017-07-20 at 15 21 32](https://user-images.githubusercontent.com/9196888/28417021-28e6f982-6d5f-11e7-9b37-bf05985107c4.png)

![screen shot 2017-07-20 at 15 25 02](https://user-images.githubusercontent.com/9196888/28417154-a37789d2-6d5f-11e7-9c6c-88d7cfa7a65a.png)

**Comment by adamwathan** [comment] 2017-07-20 12:27
How did you run `valet install`? Were you your normal user or sudo'd into root by any chance?

**Comment by MehmetNuri** [comment] 2017-07-20 12:35
@adamwathan  i was run this command without root

```
valet install
```

**Comment by mattstauffer** [comment] 2018-01-05 04:49
Closing as duplicate of #321

**Closed by mattstauffer** 2018-01-05 04:49 UTC

**Comment by mattstauffer** [comment] 2018-01-05 04:52
This seems to be a more robust discussion about the `domain` error @MehmetNuri saw above:

https://github.com/laravel/valet/issues/282
