### ISSUE TITLE
Bug passing IP as a param.

### ISSUE THREAD

**Issue by tiagocardosoweb** [laravel/valet#188] opened 2016-10-09 21:58 UTC
Hello there, I found a bug where if you pass an IP as param the Valet just crashes.

Route::get('{ip}/banner', 'ServerController@banner')->name('banner');
Example: http://laravel.dev/46.101.1.92:4499/stats/

Perhaps it's not allowed to use a colon in parameters?

```
<b>Notice</b>:  Undefined index: extension in <b>/Users/tiagocardoso/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php</b> on line <b>122</b><br />
```

Greetings,
Tiago

**Comment by adamwathan** [comment] 2016-10-09 22:03
Hey Tiago thanks for the report, can you push up an open source Laravel
repo that replicates the issue so I can pull it down to troubleshoot? Just
something with the minimal route setup necessary to recreate the problem.

Thanks!

**Comment by tiagocardosoweb** [comment] 2016-10-09 22:13
Here we go :)
https://github.com/tiagocardosoweb/colon-valet

**Comment by adamwathan** [comment] 2016-10-09 23:50
Seems like the problem is that PHP's `parse_url` blows up in this case :/ Will have to think about how to get around this in a non-horrible way :(

**Comment by adamwathan** [comment] 2016-10-10 00:16
Think this will fix it, try pulling down master and re-running `valet install` and seeing if you run into any other issues:

https://github.com/laravel/valet/commit/76c1fdb8c6e6daf3b261cb423ddae18b6fa82204

**Comment by tiagocardosoweb** [comment] 2016-10-10 00:26
It fixes the problem, but I hope it won't interfere with other stuff, maybe lets keep the issue open and see if other people run into another problem.

Thanks @adamwathan

**Comment by adamwathan** [comment] 2016-10-13 23:07
Doing some clean up, gonna close this one as resolved.

**Closed by adamwathan** 2016-10-13 23:07 UTC
