### ISSUE TITLE
add new cli cmnd to show the valet folder path

### ISSUE THREAD

**Issue by ctf0** [laravel/valet#645] opened 2018-09-30 18:18 UTC
based on the recent changes to the valet folder path from `~/.valet` to `~/.config/valet` which have caused a havok for quite a number of users, can we have a new cmnd that simply shows the current correct path of valet ? ex.
```
$ valet path
> ~/.config/valet
```

**Comment by drbyte** [comment] 2018-09-30 18:31
@ctf0 wrote:
> "caused a havok for quite a number of users"

Where is this "number of users" you speak of? Please post links.

And where are they discussing this "havok"? It would be helpful to see all the discussions where they explain the details of the exact problem they're having, and what specific workflow has been interrupted by the change. Please post links.

And now for **you** specifically, what exactly is it you were wanting to browse the `.config/valet` folder for?
Understanding your specific problem, in full detail, will help determine the best way to implement something like you suggest, if it is done.

**Comment by ctf0** [comment] 2018-09-30 20:32
for instance https://github.com/laravel/valet/issues/635 ?

**Comment by drbyte** [comment] 2018-09-30 23:38
1. #635 is unrelated to "needing to know that the config dir had changed", and the actual issue there has been resolved.

2. #640 may be tangentially related, but the issue is reported as resolved

3. @ctf0 wrote:
  > using the ssl cert file paths in laravel-echo & custom drivers

Okay, fair.
The [Release Notes](https://github.com/laravel/valet/releases/tag/v2.1.0) did mention the changed dir. 
Evidently you know a [PR is in progress](https://github.com/laravel/docs/issues/4552#issuecomment-425617180) for updating the docs, since you already commented yesterday on it. (Edit: I see you or someone else has deleted your frustration-venting comment there.)

It's not my call, but I'm not convinced that another CLI command is needed. 
If it were to be added I would suggest it be named `config-directory` instead of `path` to avoid confusion with the existing `paths` command.
I defer to @mattstauffer

**Comment by mattstauffer** [comment] 2018-09-30 23:48
From what I can see, there's a single need for this and everything else is irrelevant. Let me know if I'm wrong on that.

I haven't seen this "SSL cert file paths in laravel-echo and custom drivers"; is it something with a useful solution outside of this relatively un-useful command? Thanks @drbyte for your research.

**Comment by drbyte** [comment] 2018-10-01 00:02
> From what I can see, there's a single need for this and everything else is irrelevant. Let me know if I'm wrong on that.

That's how I read it also.

> I haven't seen this "SSL cert file paths in laravel-echo and custom drivers"

I'm assuming that they had some reason to edit a custom Valet driver they'd installed. Not sure why it would be needed, but knowing the correct path would be relevant.
And for laravel-echo, I suppose if they're doing something in their app config that requires hard-coding a path to a specific SSL cert file, then they'd be confused by the path change. 

The relocation of config files to a standard location is seamless as far as I can tell, and the devs I've talked to about it, even at a meetup this week, have had no negative impact from the change.

Nevertheless it would be good to get the docs PR merged.

**Comment by ctf0** [comment] 2018-10-01 05:55
@drbyte 

after upgrading i had a very similar issue as https://github.com/laravel/valet/issues/640#issuecomment-424098352 , also the https://github.com/laravel/valet/issues/635#issuecomment-425617451 can shows clearly the frustration i had for almost 2 hrs just to find by pure luck that the problem was related to valet not the other 6 libs i upgraded at the same time.

>  I see you or someone else has deleted your frustration-venting comment there.

it was me as it was in the wrong place which then moved to https://github.com/laravel/valet/issues/635

@mattstauffer 

>  I haven't seen this "SSL cert file paths in laravel-echo and custom drivers"

for the ssl check https://github.com/tlaverdure/laravel-echo-server#configurable-options which is needed if serving over https

**Comment by mattstauffer** [comment] 2018-10-01 15:39
Yah, I see what you had happen here, but you would've had to know to look for this command to see where your config directory is... which would've required you to go look at the repo... which would've, hopefully, led you to look at the changelog.

I understand that changes happening to the syntax of a project can break things in unexpected ways and I hope we're able to do a great job of helping people be minimally negative impacted by those changes.

But I can't see how this command would have prevented any of your difficulty or would prevent it for anyone in the future.

Am I maybe just missing something?

Thanks! And yah, I think that if you saw all those package log change logs during upgrade it would be nice. One thing I do is try to be very cautious with my composer update calls, and preferably update one library at a time rather than all of them at once. But I get that that introduces cost.

**Comment by ctf0** [comment] 2018-10-01 16:13
> but you would've had to know to look for this command to see where your config directory 

not really, because when u try to run echo, u will get an error of wrong cert path, 
- which usually the next step would be checking the path manually on the disk 
- but you wont find it, so next step would be opening valet and checking if it even there and working usually by `valet -h` 
- and now will find a helper cmnd `like the one that tells you if you are on the latest version or not` which will help you figure out if the path has changed & if you dont need to keep pulling ur hair off or it something else that have cuzed that.

**Comment by mattstauffer** [comment] 2018-10-01 17:06
Right, but the path is not changing again, and you would've had to check the docs to know that that even was added, and when you checked the docs you would've seen this update.

I get that you wish that this was different last time, but I can't see how this is going to help anyone going forward. Thanks!

**Closed by mattstauffer** 2018-10-01 17:06 UTC
