### ISSUE TITLE
Valet status command

### ISSUE THREAD

**Issue by welcoMattic** [laravel/valet#251] opened 2016-12-12 09:45 UTC
It would be nice to have a `valet status` command, to know if valet is currently started or stopped.
With this kind of command we could call it from any menu-bar software like [BitBar](https://github.com/matryer/bitbar), and get a visual indication of valet status.

**Comment by shiroamada** [comment] 2016-12-14 10:25
`valet start` also not really indicate nginx is really start. I got wrong config file setup in `/Users/shiroamada/.valet/Nginx/mywebsite.dev`, but valet start still show it successfully started. But actually my nginx is not started. I need to `sudo nginx` to check what's really goes wrong.

**Comment by antonioribeiro** [comment] 2016-12-17 05:35
@shiroamada, sent a PR to fix your issue: https://github.com/laravel/valet/pull/268

**Comment by lukeed** [comment] 2016-12-28 14:42
#17

**Comment by omdjinmesem** [comment] 2017-10-03 09:04
It this command `valet status` already implemented yet? 
I cant find`status` on the command list

**Comment by drbyte** [comment] 2018-09-18 22:19
> It this command `valet status` already implemented yet?

No, however, valet is more verbose about errors occurring when re/starting nginx.

Nowadays you can run: `brew services list` to get a status.

**Comment by mattstauffer** [comment] 2018-09-19 02:26
Closing; if this is re-suggested given the current state of things we can start a new discussion.

**Closed by mattstauffer** 2018-09-19 02:26 UTC
Labels: enhancement

**Comment by audetcameron** [comment] 2021-09-24 16:24
> > It this command `valet status` already implemented yet?
> 
> No, however, valet is more verbose about errors occurring when re/starting nginx.
> 
> Nowadays you can run: `brew services list` to get a status.

what if brew services list shows nothing is running (but valet is running and working)  is there some sort of permission disconnect or something that is going on?  I confirmed my foo.test site is running but nginx and PHP show as stopped 
![image](https://user-images.githubusercontent.com/6738453/134708851-44fcc158-f715-460a-95f6-7637ee595528.png)

**Comment by mayrac2022** [comment] 2022-11-30 19:07
I think it would be really nice to have this command. `brew services list` doesn't explicitly say Valet, so we have to figure it out.

**Comment by mattstauffer** [comment] 2022-12-26 16:26
I'm considering adding this command to v4.

Here's what I'm thinking.

Valet isn't ever actually "running" or "not running". *But*, it can have a boolean type status: it can be "configured correctly with all its services running" or "something is wrong, whether a service not running, a configuration error, or Valet not installed at all".

Would that be helpful?

If so, I'm imagining it would check:
- Is Valet installed
- Are all services (Nginx, Dnsmasq, etc.) running via Brew
- Are all configuration items non-erroring (e.g. check the Nginx config, manually check our local Valet config files, etc.)

If so, it would return a positive return code, together with some nice graphics showing success.

If not, it would return a negative return code, together with the same graphics showing errors.

**Comment by philbraun** [comment] 2023-01-04 08:43
Having a valet status sommand would be really nice, especially if the output is less confusing than `brew services list`.
(Here's what this looks like here; Valet is running without any problems even before `valet start`, doing the full `composer global update` > `valet install` doesn't change anything to these outputs)
<img width="590" alt="Bildschirm­foto 2023-01-04 um 09 36 52" src="https://user-images.githubusercontent.com/8843647/210515621-408eac99-cda7-4135-a353-921db488f34e.png">
