### ISSUE TITLE
In Brew.php line 187: Unable to determine linked PHP.                                    

### ISSUE THREAD

**Issue by orangeShadow** [laravel/valet#533] opened 2018-03-08 21:50 UTC
I try methods: composer global update, install php 72, brew upgrade,  but error repeat and repeat ? what can i do, to run service ? valet version 2.0.8

**Comment by drbyte** [comment] 2018-03-11 04:34
@donaldallen wrote:
> It would be nice if Valet had some suggestions on what to do when "Unable to determine linked PHP." comes up.

Two code references:
https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L178-L179
In this one it's looking to ensure that the `php` binary is linked. So, if you've unlinked all the installed PHP versions, then you'll get that error message.

Next it moves on to verify that the linked php binary is a supported one, per this list:
https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L53-L56

**Comment by uruloke** [comment] 2018-03-13 07:13
Getting some error here, tried to follow my symlink and it looks like this `../Cellar/php/7.2.2_14/bin/php`. 

[Looking at how it matches,](https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L185) it looks for a full path containing one of the supported versions.

The supported php version looks for strings named like this `php72`, which of course is not in the path.

**Comment by scherii** [comment] 2018-03-13 07:47
@uruloke Should this not be caught [by the first item](https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L55) `php`?

**Comment by orangeShadow** [comment] 2018-03-13 07:56
uruloke, Yes, I commented locally this checking, and all is working, but it is not good decision

**Comment by uruloke** [comment] 2018-03-13 07:59
@scherii You are right, it should be caught by that, didn't see it. Gotta test this out a little locally and see if I can find an great solution.

**Comment by uruloke** [comment] 2018-03-13 08:48
After cloning the repo I can't reproduce the error, lol. 
If OP or someone else could tell how to reproduce the error, I will gladly try to fix it.

**Comment by orangeShadow** [comment] 2018-03-13 08:53
Try brew update php veriosn

**Comment by uruloke** [comment] 2018-03-13 09:13
@orangeShadow Just uninstalled php72 then installed php71, linked to php71, upgraded to php72 and linked to php72, then ran valet start and everything seems to work.

**Comment by orangeShadow** [comment] 2018-03-13 11:15
@uruloke, Can you write your file path and name for php link

**Comment by lesaff** [comment] 2018-03-16 17:53
Brew has promoted `php7.2` to core, so it is called `php` now. 
https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L185 will always throw exception until the logic is revised.

**Comment by martijnvdven** [comment] 2018-03-18 17:06
@scherii,

> Should this not be caught [by the first item](https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L55) `php`?

You’d think that. But for some reason it didn’t for me on the path `../Cellar/php/7.2.3_2/bin/php`… But when I added an item `'7.2.3_2'` to the array on that line all worked fine. No clue what’s tripping it up there.

**Comment by Zegnat** [comment] 2018-03-18 17:51
@scherii,

> Should this not be caught [by the first item](https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L55) `php`?

You’d think that. But for some reason it didn’t for me on the path `../Cellar/php/7.2.3_2/bin/php`… But when I added an item `'7.2.3_2'` to the array on that line all worked fine. No clue what’s tripping it up there.

**Comment by MelMacaluso** [comment] 2018-04-13 21:46
```
brew unlink php && brew link php
brew services restart --all
composer global update
valet start

```

That fixes it.

**Comment by delino12** [comment] 2018-04-25 14:53
ln -s /usr/local/Cellar/php71/7.1.16_1/bin /usr/local/bin/php


➜  ~ valet install
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
Updating PHP configuration...
Restarting php@7.1...
Restarting dnsmasq...
Restarting nginx...

**Comment by kroko** [comment] 2018-04-25 15:37
wild guess that most people here having the issue only care if it's 7.1+ and thus are fighting an unnecessary fight. if possible just trash all php things from the system with `uninstall, doctor, cleanup` and just install newest php (currently 7.2) and formula name will be `php` not `php@version`, it has been fixed in brew core formula names [for some time](https://github.com/Homebrew/homebrew-core/commit/4dbb4adf8ebdccc947c2f20f08e8e3ca06c023a3#diff-1df8783161e0d794f82b4b77825ee6b8R137) and `install php@version` is used only if you [explicitly want older php](https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json#L141).

**Comment by khadkaPratik** [comment] 2018-04-26 10:35
`valet install`
> In Brew.php line 182:
>   Unable to determine linked PHP.

`brew unlink php && brew link php`
> Error: No such keg: /usr/local/Cellar/php

`brew install php` worked in my case to resolve the issue

**Comment by mikoop79** [comment] 2018-05-24 00:02
this worked for me...

brew unlink php

brew link --overwrite php

valet install

**Comment by eddy80310** [comment] 2018-05-24 00:06
If you follow donaldallen's comment and it still doesn't fix it you can check if it's symlinked correctly.

```
$ which php
/usr/local/opt/php@7.1/bin/php
```

Then create a symlink to where this is looking for it: https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L181

```
ln -s /usr/local/opt/php@7.1/bin/php /usr/local/bin/php
```

That was the fix on mine.

**Comment by orangeShadow** [comment] 2018-05-29 11:47
Hi, I found problem !!!!

```
return $this->supportedPhpVersions()->first(function ($version) use ($resolvedPath) {
            $resolvedPathNormalized= preg_replace('/([@|\.])/', '', $resolvedPath);
            $versionNormalized = preg_replace('/([@|\.])/', '', $version);
            return strpos($resolvedPathNormalized, "/$versionNormalized/") !== false;
        }, function () {
            throw new DomainException("Unable to determine linked PHP.");
        });
```
In line 187 $version is a key of constant's array, but if you set second parameter it would be a $version 

```
return $this->supportedPhpVersions()->first(function ($key, $version) use ($resolvedPath) {
            $resolvedPathNormalized= preg_replace('/([@|\.])/', '', $resolvedPath);
            $versionNormalized = preg_replace('/([@|\.])/', '', $version);
            return strpos($resolvedPathNormalized, "/$versionNormalized/") !== false;
        }, function () {
            throw new DomainException("Unable to determine linked PHP.");
        });
```

**Comment by OZZlE** [comment] 2018-06-02 17:04
The code seems to check only if php is a symlink, however I just installed MacOs High Sierra in the latest version and it comes with PHP 7.1.14 which should be fine in many cases, might even be wanted by some systems that don't fully work with PHP 7.2...

So I think the logic should take into consideration that the systems built in PHP version might be okay as well!

Brew.php:

        if (!$this->files->isLink('/usr/local/bin/php')) {
            throw new DomainException("Unable to determine linked PHP.");
        }

**Comment by immarina** [comment] 2018-06-05 19:53
Im completely lost, ive tried every solution posted before and nothing seems to work.
Ive made sure brew and composer are both up to date, tried completely removing valet and reinstalling everything from scratch and i keep getting the same error.

I dont know why valet keeps trying to install php71 which is already installed via brew and showing in the right folder

```which php
/usr/local/bin/php
php -v
PHP 7.1.18 (cli) (built: May 25 2018 19:18:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans```

```valet install
Password:
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
Installing php71...
Error: homebrew/dupes was deprecated. This tap is now empty as all its formulae were migrated.
Error: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.
[php71] is not installed, installing it now via Brew... 🍻
Updating PHP configuration...

In Brew.php line 187:

  Unable to determine linked PHP.```

**Comment by drbyte** [comment] 2018-09-19 03:41
I think this can be closed, as multiple improvements have been made to address the homebrew changes that precipitated this.

**Closed** 2018-09-19 13:01 UTC

**Comment by masterdef** [comment] 2018-11-08 20:12
fixed by:

$ ln -s /usr/local/opt/php@7.0/bin/php /usr/local/bin/php

**Comment by AK-PapaSoft** [comment] 2018-11-24 16:11
My way to fix this was ti rewrite current php version: `brew link php@7.1 --force --overwrite`
That worked for me in similar case. If you have questions in the whole process - ping me as well. Probably, I can help ;)

**Comment by hezll** [comment] 2018-12-08 11:34
> `valet install`
> 
> > In Brew.php line 182:
> > Unable to determine linked PHP.
> 
> `brew unlink php && brew link php`
> 
> > Error: No such keg: /usr/local/Cellar/php
> 
> `brew install php` worked in my case to resolve the issue
> 
> `valet install`
> 
> > Valet installed successfully!

this works for me too. 

(I try to follow the docs on laravel.com to run brew install php@7.2, but it failed)

**Comment by mattstauffer** [comment] 2018-12-09 03:53
@hezll If "Unable to determine linked PHP" is on your line 182, you're not running the latest version of Valet. Please update and try again if you have any issues. Thanks!

**Comment by andrey-bondarenko** [comment] 2018-12-10 13:02
This helped me

in file: /Users/<user>/.composer/vendor/weprovide/valet-plus/cli/Valet/Brew.php

on line: 16
`   const PHP_V72_BREWNAME = 'php'; `

change to :

`const PHP_V72_BREWNAME = 'php@7.2';`

**Comment by mattstauffer** [comment] 2018-12-10 13:13
@andrey-bondarenko that path shows you're using Valet-Plus, which is a poorly-named alternative which has no connection to this project at all :)

**Comment by s3w47m88** [comment] 2018-12-11 01:56
I'm on MacOS 10.14 and had to `brew link --force php@7.2`

**Comment by vijaybajrot** [comment] 2018-12-16 10:34
> `valet install`
> 
> > In Brew.php line 182:
> > Unable to determine linked PHP.
> 
> `brew unlink php && brew link php`
> 
> > Error: No such keg: /usr/local/Cellar/php
> 
> `brew install php` worked in my case to resolve the issue
> 
> `valet install`
> 
> > Valet installed successfully!

Work for me also.

**Comment by tucq88** [comment] 2018-12-26 00:18
Now it's problem with line 195 with latest Valet T_T 
Tried install php@7.2 or php (aka php@7.3) still not work

**Comment by thomasbyoung** [comment] 2018-12-27 15:48
tucq88 are you still having the issue at line 195? I am as well, anyone have any ideas?

**Comment by tucq88** [comment] 2018-12-27 16:13
@thomasbyoung Yeah still mate, I'm going back to Vagrant which is much more painful :(

**Comment by shane-smith** [comment] 2018-12-28 12:10
Just purchased a new machine. Valet is working perfectly on the old one. Getting the error listed above (by other people, line 195) on a fresh install.

1. Updated to macOS Mojave 10.14.2
2. Started following the steps at https://laravel.com/docs/5.7/valet#installation - with one exception, I installed php@7.1 instead of php@7.2 (as I wanted to stick with the version I know my current projects are tested on, for now).
3. The `valet install` command fails with the error mentioned:

```
In Brew.php line 195:
                                   
  Unable to determine linked PHP.
```

The history of this computer is nothing. It's new. Installed PHP 7.1, Valet problem starts immediately on first install.

**which php**
```
/usr/bin/php
```
**php -v**
```
PHP 7.1.19 (cli) (built: Aug 17 2018 20:10:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```
**brew services list**
```
Name    Status  User   Plist
nginx   stopped        
php@7.1 started shanes /Users/shanes/Library/LaunchAgents/homebrew.mxcl.php@7.1.plist
```
**brew info php**
```
php: stable 7.3.0 (bottled)
General-purpose scripting language
https://secure.php.net/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd ✘, pkg-config ✘
Required: apr ✔, apr-util ✔, argon2 ✘, aspell ✔, autoconf ✔, curl-openssl ✔, freetds ✔, freetype ✔, gettext ✔, glib ✔, gmp ✔, icu4c ✔, jpeg ✔, libpng ✔, libpq ✔, libsodium ✘, libzip ✔, openldap ✔, openssl ✔, pcre ✔, sqlite ✔, tidy-html5 ✔, unixodbc ✔, webp ✔
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.3/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 43,800 (30 days), 122,653 (90 days), 383,832 (365 days)
install_on_request: 39,843 (30 days), 111,615 (90 days), 346,530 (365 days)
build_error: 0 (30 days)
```

**Comment by shane-smith** [comment] 2018-12-28 12:19
Hmm, interesting.

**brew unlink php@7.1 && brew link php@7.1 --force**
```
Unlinking /usr/local/Cellar/php@7.1/7.1.25... 0 symlinks removed
Linking /usr/local/Cellar/php@7.1/7.1.25... 25 symlinks created
```

The symlinks were initially missing.

Afterwards, `valet install` works. 💯

@tucq88 and @thomasbyoung - try one of the following, depending on what version of PHP you have installed on your system:
- `brew unlink php@7.2 && brew link php@7.2 --force`
- `brew unlink php@7.1 && brew link php@7.1 --force`
- `brew unlink php && brew link php --force`

Then re-try the `valet install` command.

**Comment by drbyte** [comment] 2018-12-31 14:18
@tucq88 please answer the questions I posted above.

**Comment by OZZlE** [comment] 2019-01-02 08:05
> Hmm, interesting.
> 
> **brew unlink php@7.1 && brew link php@7.1 --force**
> 
> ```
> Unlinking /usr/local/Cellar/php@7.1/7.1.25... 0 symlinks removed
> Linking /usr/local/Cellar/php@7.1/7.1.25... 25 symlinks created
> ```
> The symlinks were initially missing.
> 
> Afterwards, `valet install` works. 💯

How is it interesting? It's an obvious bug that these people won't fix for some reason... See: https://github.com/laravel/valet/issues/533#issuecomment-394101964

**Comment by mattstauffer** [comment] 2019-01-02 14:05
@OZZlE These people? Please direct me to the pull request where you fixed it and I'll be more than happy to review it.

**Comment by mattstauffer** [comment] 2019-01-02 14:10
For anyone who is curious, we're taking a look and trying to figure out a good solution. "Just allow non-Homebrew PHP" may not be a good enough solution; "just allow non-symlinks" may not be a good enough solution; "I have to run a Homebrew command to get my Valet working and therefore it's Valet's fault" is a bad take.

If anyone has all of this in their brain and can fully conceptualize the best fix, please, create a new issue and/or pull request and guide us here. Otherwise, please respect the amount of work @drbyte has put into helping people here--with no benefit or payment to himself.

**Comment by shane-smith** [comment] 2019-01-08 01:21
Perhaps a quick fix (meanwhile) is to document any workarounds as part of the install instructions. I suspect anyone installing this on a fresh machine with latest macOS will run into the problem.

This looks to be the place: https://github.com/laravel/docs/blob/5.7/valet.md#installation

I may be able to submit something myself, but likely not this week.

**Comment by OZZlE** [comment] 2019-01-08 07:03
> For anyone who is curious, we're taking a look and trying to figure out a good solution. "Just allow non-Homebrew PHP" may not be a good enough solution; "just allow non-symlinks" may not be a good enough solution; "I have to run a Homebrew command to get my Valet working and therefore it's Valet's fault" is a bad take.
> 
> If anyone has all of this in their brain and can fully conceptualize the best fix, please, create a new issue and/or pull request and guide us here. Otherwise, please respect the amount of work @drbyte has put into helping people here--with no benefit or payment to himself.

Sorry I was a bit cranky :) What about doing like this: if php is exists and is not a symlink; output this php with version and ask the user if they would like to keep it or update to the latest php, if they go with latest then force symlink it to that.

**Comment by mattstauffer** [comment] 2019-01-14 04:36
I think we have a fix (written by @drbyte, no surprise) on master. Anyone who wants to take a look can; I'm letting it sit there for a few days before I release, but I'll likely release within the next day or two.

**Comment by Vinai** [comment] 2019-01-28 14:08
Is this out already?

**Comment by mattstauffer** [comment] 2019-01-28 16:04
@Vinai Yep: https://github.com/laravel/valet/releases/tag/v2.1.6

**Comment by aado29** [comment] 2019-02-28 19:24
So to solve the problem, simply create the directory with `sudo mkdir /usr/local/sbin` and then set the correct ownership on it with `` sudo chown -R `whoami`:admin /usr/local/sbin ``.

then:
  
```
$ brew unlink php && brew link php
$ brew services restart --all
$ composer global update
$ valet start
```

**Comment by fsluijs** [comment] 2019-04-15 21:03
This is what resolved it for me:
`$ brew link php@7.2`
`$ valet use php@7.2`

**Comment by ayman-alkom** [comment] 2019-04-25 14:05
try to close the terminal & restart it again

**Comment by icarojobs** [comment] 2019-08-20 23:44
Type of @delino12 solve my problem! Thanks dude!

**Comment by brianhogg** [comment] 2019-09-01 15:21
Returning to this thread I already replied to after spending an hour trying to get it to work :)

`brew install php` doesn't install 7.3 but grabs 7.2.
`brew link php@7.3` gives `Warning: php@7.2 is keg-only and must be linked with --force`

and no matter what `valet start` or `valet restart` gives the unable to determine linked php error. Stumped.

**Comment by drbyte** [comment] 2019-09-02 11:34
@brianhogg Ya, the `brew update` should have made sure you have the latest version endpoints to install for.
My first reaction is that that maybe suggests something amuck with your homebrew install.
I'd start by running `brew doctor` and exploring its suggestions.

A more aggressive advanced step you could explore is to delete your `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` directory, and then run `brew doctor` again to have it re-install the core taps that are used for installing php with brew.

Also, what does `valet --version` say? Today the latest is 2.3.3.

**Comment by pmochine** [comment] 2019-10-22 19:05
@delino12 helped me a lot! However, first you need to understand that you still have two php version on your mac. 

When you use an empty .php file and write down `phpinfo();` you might see that the version is not correctly installed, even though if you type down `php -v` in your terminal you see the newest version.

What I found out is that you need to create a new symlink for your mac. 

1. Find out where your newest php is. Use for example `which php` or `brew list php`
2. Now you need to remove the local php that is installed with `rm -f /usr/local/bin/php`. This removes the php bin file.
3. Now we are creating a symlink to the newest php bin file just by: `ln -s /usr/local/Cellar/php/7.3.10/bin /usr/local/bin/php` (Warning! Please update the first path to the path you saw with `which php`)

Now it works for me :) I hope it helped you as well

**Comment by drbyte** [comment] 2019-10-22 20:03
Rather than manually linking, Homebrew can do the symlinking for you:

```sh
brew unlink php@7.2
brew link php@7.3
```

Sometimes adding `--force` can be useful.

**Comment by grafxflow** [comment] 2019-11-25 10:25
Anybody using macOS 10.15 the file to amend now id ~/.zshrc.

Example being.

```
# export PATH="/usr/local/opt/php@7.1/bin:$PATH"
# export PATH="/usr/local/opt/php@7.1/sbin:$PATH"
export PATH="/usr/local/opt/php@7.2/bin:$PATH"
export PATH="/usr/local/opt/php@7.2/sbin:$PATH"
```

**Comment by LeRoyJulian** [comment] 2019-11-30 09:55
After updating to PHP 7.4 : 

`In Brew.php line 251:
                                                     
  Unable to determine linked PHP when parsing '7.4' `

**Comment by 6thCode** [comment] 2020-03-13 11:23
I had the same issue, and this was what I did to fix it:

Check your current php version
`brew unlink php` 
`valet use php@current version ( eg:- valet use php@7.4 )`
`brew services restart --all`
`composer global update`
`valet start`

Hopefully, this helps🙂

**Comment by israelguido** [comment] 2020-03-23 18:31
Im use Valet+ this code bellow help me:
brew unlink valet-php@7.2 && brew link --force valet-php@7.2

**Comment by drbyte** [comment] 2020-03-23 18:33
> Im use Valet+ this code bellow help me:
> brew unlink valet-php@7.2 && brew link --force valet-php@7.2

Discussion about `Valet-Plus` should be done in their repository.

**Comment by israelguido** [comment] 2020-03-23 18:38
> > Im use Valet+ this code bellow help me:
> > brew unlink valet-php@7.2 && brew link --force valet-php@7.2
> 
> Discussion about `Valet-Plus` should be done in their repository.

sorry!

**Comment by drbyte** [comment] 2020-03-23 18:42
@israelguido here's clarification why:
Otherwise the advice given might be irrelevant/incomplete/incorrect. Such as in this case, where valet-php doesn't exist in official Laravel Valet.

**Comment by AlvinQinwen** [comment] 2020-07-20 03:29
```Valet doesn't support PHP version: php@7.4 (try something like 'php7.2' ins  
  tead)  ```
 but some vender need php@7.4 
how i to do?

**Comment by mattstauffer** [comment] 2020-07-23 16:20
@AlvinQinwen please open a new issue if you have questions. Also, please update your copy of Valet and re-test before you do.

**Comment by ivansempijja** [comment] 2024-02-27 17:12
I had the same issue using php 8.3, All the above solutions did not work.
what I had to do was to update valet

`composer global update`
`composer global require laravel/valet`
`valet install`

this should do the trick

**Comment by 7morimax** [comment] 2024-04-11 18:30
> I've had the same problem tonight, and here's what I did to get it running:
> 
> `brew unlink php && brew link php` `brew services restart --all` `composer global update` `valet start`
> 
> It would be nice if Valet had some suggestions on what to do when "Unable to determine linked PHP." comes up.

Funiconó para mi, gracias!

**Comment by drbyte** [comment] 2024-06-18 16:49
> I have this problem after finsih
> composer global require `cretueusebiu/valet-windows`

Probably best to post your problem in their github page.
