### ISSUE TITLE
Running Valet with ExpressVPN

### ISSUE THREAD

**Issue by mohnjatthews** [laravel/valet#527] opened 2018-02-27 12:50 UTC
Hi all, 

I'm running Laravel Valet 2.0.7 on macOS High Sierra (10.13.3) with ExpressVPN. When I have the VPN client running, none of my Laravel sites work (I get a *This site can't be reached* error). When I turn my VPN off, the Laravel sites work fine.

Has anyone else encountered this issue? Obviously the workaround is to not use my VPN while coding, but if I'm working while out and about, I'd rather have a secure connection I can trust.

**Comment by drbyte** [comment] 2018-02-27 15:21
I'm guessing there's some conflict between how your VPN software works vs how dnsmasq works.

When I use NetShade VPN I can still access all my valet sites.

Might be worth testing some edits to your `dnsmasq.conf` settings. I posted mine here awhile back: https://github.com/laravel/valet/issues/115#issuecomment-241275816

**Comment by atmediauk** [comment] 2018-08-05 19:26
Having the same issue as well. Tried editing dnsmasq.conf as suggested above but unfortunately still no luck :( 

Laravel Valet 2.0.12
MacOS High Sierra (10.13.6)

**Comment by drbyte** [comment] 2018-08-05 22:27
It sounds like the VPN client is overriding the DNS provided by dnsmasq. 
You should be able to fix this by changing the sort-order of dns providers in your network DNS settings.

**Comment by aerni90** [comment] 2018-09-18 05:58
Having the same problem with ExpressVPN and Laravel Valet. Anyone found a solution?

**Comment by mohnjatthews** [comment] 2018-09-18 13:28
I wasn't able to find a solution @aerni90. I emailed ExpressVPN when this whole thing happened months ago, but they weren't able to figure anything else. I've now moved VPN provider (ProtonVPN) and no longer get this problem.

**Comment by paihz** [comment] 2018-09-23 23:06
> Having the same problem with ExpressVPN and Laravel Valet. Anyone found a solution?

I connect using PPTP,problem solve.

**Comment by drbyte** [comment] 2018-09-23 23:50
I think the title of this issue should reflect that the problem is with ExpressVPN.
And probably close the issue.

**Closed** 2018-09-24 05:15 UTC

**Comment by markvdputten** [comment] 2018-10-08 20:25
I had this same issue, but there seems to be a quite simple solution for this, when you open the preferences of ExpressVPN and go to Advanced, you can de-select the option "DNS: Only use ExpressVPN DNS servers while connected".

I did this, after which Valet is working as expected again, also I ran the dns leakage test on the ExpressVPN website and all still seems to be just fine...

**Comment by aerni90** [comment] 2018-10-09 13:58
@markvdputten Thanks for this solution. Works great!

**Comment by danny-freeman** [comment] 2020-03-03 08:47
@markvdputten Absolute life saver been messing around with all the settings for a few days now. Lost so much work time. Thank you!

**Comment by jethromay** [comment] 2021-01-30 06:12
@markvdputten life saver!

**Comment by sanwinmaung** [comment] 2021-04-02 05:16
> I had this same issue, but there seems to be a quite simple solution for this, when you open the preferences of ExpressVPN and go to Advanced, you can de-select the option "DNS: Only use ExpressVPN DNS servers while connected".
> 
> I did this, after which Valet is working as expected again, also I ran the dns leakage test on the ExpressVPN website and all still seems to be just fine...

Thanks @markvdputten , you save my time.

**Comment by adddz** [comment] 2021-07-13 00:03
New version of ExpressVPN and this option seems to be missing. Am I the only one?

**Comment by jethromayuk** [comment] 2021-07-23 07:52
@adddz 

After updating I'm experiencing this issue too and confirm the above-mentioned setting isn't available anymore..

**Comment by adddz** [comment] 2021-07-23 08:27
> @adddz
> 
> After updating I'm experiencing this issue too and confirm the above-mentioned setting isn't available anymore..

Please try to message them as well. I already reported that this will all Laravel Valet + ExpressVPN users. For now, I had to downgrade to a previous version.

**Comment by jethromayuk** [comment] 2021-07-23 08:28
@adddz I will do - which version did you downgrade to?

**Comment by adddz** [comment] 2021-07-23 09:08
> @adddz I will do - which version did you downgrade to?

Version 10.3.0 (49). The customer support sent me the link to download it.

**Comment by jethromayuk** [comment] 2021-07-23 09:11
@adddz great thanks will give that a try.. I have also mailed ExpressVPN. It's an annoying issue!

**Comment by icemancast** [comment] 2021-08-03 21:59
Same here any updates?

**Comment by mattstauffer** [comment] 2021-08-04 14:34
@icemancast 🤷🏻‍♂️ As far as I can tell this is an ExpressVPN issue, not a Valet issue.

**Comment by icemancast** [comment] 2021-08-11 01:28
Okay will reach out to them then thanks @mattstauffer

**Comment by GonrasK** [comment] 2021-09-08 14:37
It would be great if any of the people who contacted ExpressVPN will share their solution, if there's any..

**Comment by danny-freeman** [comment] 2021-09-08 14:42
I reached out to ExpressVPN and they kept saying it was an issue with Valet clearly didn't have much knowledge on their own product. I had to downgrade to Version 10.0.0 for Laravel Valet to work. They have no intentions of fixing the issue.

**Comment by adddz** [comment] 2021-09-09 21:16
Same here. To be honest I'm using the version of ExpressVPN, it just works fine.

**Comment by aerni** [comment] 2021-11-24 08:40
I changed back to using NordVPN because of this issue. No problems now.

**Comment by colourgarden** [comment] 2022-04-12 08:21
Also confirming disabling "Only use ExpressVPN DNS servers while connected” works.

One liner to downgrade ExpressVPN with Homebrew:

```
curl -L https://raw.githubusercontent.com/Homebrew/homebrew-cask/db760192b7c159ceb0db7583da4e6ccd9f464663/Casks/expressvpn.rb > $(find $(brew --repository) -name expressvpn.rb) && brew reinstall expressvpn
```

**Comment by mokhosh** [comment] 2022-07-21 10:30
> One-liner to downgrade ExpressVPN with Homebrew:

I get
```
zsh: no such file or directory:
```

**Comment by colourgarden** [comment] 2022-07-21 11:15
@mokhosh Can you post the rest of the error?

**Comment by mokhosh** [comment] 2022-07-21 12:26
> @mokhosh Can you post the rest of the error?

that's the whole error

**Comment by colourgarden** [comment] 2022-07-21 13:14
This is hard to debug without further information. I'd suggest it may be an issue with your Homebrew or zsh setup rather than the command itself. What do you get when running `brew doctor`?

**Comment by mokhosh** [comment] 2022-07-21 15:47
```
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
```
and then a long list of nodejs header files.

**Comment by colourgarden** [comment] 2022-07-22 08:13
@mokhosh Do you already have ExpressVPN installed? The one-liner I posted will only work if you already have an `expressvpn.rb` Homebrew file to replace.

**Comment by mokhosh** [comment] 2022-07-22 08:14
i have it but havent installed it through brew. thats the issue isnt it?

**Comment by colourgarden** [comment] 2022-07-22 11:15
@mokhosh Correct. This part of the one-liner is looking for an existing `expressvpn.rb` file and then replaces it - `$(find $(brew --repository) -name expressvpn.rb)`

**Comment by doxigo** [comment] 2022-08-11 11:45
Any actionable solution besides downgrading?

**Comment by mokhosh** [comment] 2022-08-12 02:02
> Any actionable solution besides downgrading? 

Nope. I've contacted expressvpn's support and they're looking for "more demand" to add the feature back.
The only solution for now is to downgrade.

**Comment by adddz** [comment] 2022-08-12 02:43
It's actually quite ridiculous we're all having this issue with "one of the best VPNs" out there.
I really want to switch and not be stuck with a very old version of ExpressVPN.

Anybody has tried something else and can vouch for another service in terms of speed, reliability and that it works with Laravel Valet?

**Comment by doxigo** [comment] 2022-08-12 08:04
@adddz Yeah try Mullvad or IVPN
Both more privacy concerned than ExpressVPN

**Comment by mokhosh** [comment] 2022-08-12 12:41
i tried nord and switched back to express in less than an hour

**Comment by adddz** [comment] 2022-08-13 03:16
> i tried nord and switched back to express in less than an hour

Too slow?

@doxigo – I've heard good things about Mullvad. Is it fast?

**Comment by doxigo** [comment] 2022-08-13 08:24
@adddz Yeah quite okay

**Comment by mokhosh** [comment] 2022-08-13 10:16
> Too slow?

Very unstable compared to express

**Comment by lupka** [comment] 2022-09-18 19:29
My workaround for this while I had Express running (on Mac) was to add an entry to my `/etc/hosts` file for the site I'm working on (`127.0.0.1 site-domain.test`). Would be annoying if I was running the VPN all the time, but I don't need to do that so this works for me here and there as needed.

**Comment by jasperf** [comment] 2023-09-01 02:37
@lupka yeah, adding a manual line does work as well with Express VPN running still. That is a manual thing, but at least you can do both . Spent an hour debugging only to realize the VPN was causing the host not found issue .

**Comment by Recrus** [comment] 2023-09-03 13:07
Have there been any other solutions? Even installing the old version of the program did not help, but I don’t want to climb into the file system(

**Comment by doxigo** [comment] 2023-09-07 14:54
The only solution is to edit your `/etc/hosts` and add your local website there and map it to `127.0.0.1` 
like:
```
127.0.0.1 websitename.loc
```
