### ISSUE TITLE
Valet share (failed to establish a connection)

### ISSUE THREAD

**Issue by Elsingad** [laravel/valet#1214] opened 2022-03-22 09:15 UTC
- Valet Version: 2.18.10
- PHP Version: 8.1.4

### Description:
Valet share gives me the following error when opening the link:

Failed to complete tunnel connection
The connection to https://*.ngrok.io/ was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address [mywebsitehere.test:60](http://mywebsitehere.test:60/).

Make sure that a web service is running on [mywebsitehere.test:60](http://mywebsitehere.test:60/) and that it is a valid address.

The error encountered was: dial tcp: lookup mywebsitehere.test on **iphere**: no such host

### Steps To Reproduce:
valet share

**Comment by driesvints** [comment] 2022-03-22 09:21
Duplicate of https://github.com/laravel/valet/issues/1172

**Closed by driesvints** 2022-03-22 09:21 UTC
