### ISSUE TITLE
`valet use` does not stop previous php version service

### ISSUE THREAD

**Issue by cristiancalara** [laravel/valet#1177] opened 2022-01-06 16:21 UTC
- Valet Version: 2.18.4
- PHP Version: 8.1.1

### Description:
After I switch the PHP version using `valet use php@8.0`, the previous PHP@8.1 service is still running https://share.getcloudapp.com/12u0DEPN. On restart, the PHP@8.0 service will have a status of 'error' when running `sudo brew services restart` https://share.getcloudapp.com/xQuz099d

At this point, the version of PHP linked is 8.0 but the running PHP version is 8.1 (that's also the case when running `phpinfo()`).  If you run `valet use php@8.0` (I usually run this as I see an error that's caused by the site running on 8.1, so I'd expect that valet is also using 8.1), you get the warning saying that this version is already linked, and you should use `--force`

### Steps To Reproduce:
1. `valet use php`
2. `valet use php@8.0`
3. `sudo brew services list` - will show both the previous and the current service still running
4. restart computer
5. open a site `phpinfo()` - you should see PHP 8.1 (so the version used when running `valet use php`)
6. run `valet use php@8.0` - 
7. you should see a warning saying that this version is already linked - this is a bit confusing for me, as I'd expect to have php8.1 linked as shown in `phpinfo()` i.e. the linked and running version to be the same

### Debugging
I've looked a bit into this, and it seems that the intention in the code was to actually stop all the PHP services - https://github.com/laravel/valet/blob/master/cli/Valet/PhpFpm.php#L205 . But they are not actually closed because the `$this->brew->getRunningServices()` call does not return the services that are ran using `sudo` (as it's the case with PHP).

If I update the code at https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L381 and add `sudo` https://share.getcloudapp.com/WnuqEAzd  before the command, the issue above is resolved. 

### Notes
- The issue above is not really critical, as you can switch between versions and things will get fixed. But I thought it might be worth raising as after looking through the code I saw that tried to actually stop the currently running PHP services.
- While on my tests, it was always the `php` version that was launched successfully and the older one having the error - I'm not 100% sure this is consistent, as I'm not sure of the order `launchctl` uses when opening the services. 

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.18.4</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/cristian/.config/valet/Sites"
    ],
    "loopback": "127.0.0.1"
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.8",
        "laravel/installer": "^4.1",
        "beyondcode/expose": "2.0"
    },
    "require-dev": {
        "brainmaestro/composer-git-hooks": "^2.8"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/cristian/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.beyondcode/expose : exact version constraints (2.0) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.1.9 => 2.2.3)
Composer version: 2.1.9
PHP version: 8.0.14
PHP binary path: /usr/local/Cellar/php@8.0/8.0.14/bin/php
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021
cURL version: 7.80.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1m
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/cristian/.composer
Legend:
! patch or minor release available - update recommended
~ major release available - update possible
beyondcode/expose             2.0.0  ! 2.0.2  Create public URLs for local sites through any firewall and VPN.
padraic/humbug_get_contents   1.1.2  ~ 1.0.4  Secure wrapper for accessing HTTPS resources with file_get_contents for PHP 5.3+
padraic/phar-updater          v1.0.6 = v1.0.6 A thing to make PHAR self-updating easy and secure.
Package padraic/phar-updater is abandoned, you should avoid using it. No replacement was suggested.
psr/container                 1.1.2  ~ 2.0.2  Common Container Interface (PHP FIG PSR-11)
psr/simple-cache              1.0.1  ~ 3.0.0  Common interfaces for simple caching
symfony/console               v5.4.2 ~ v6.0.2 Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts v2.5.0 ~ v3.0.0 A generic function and convention to trigger deprecation notices
symfony/process               v5.4.2 ~ v6.0.2 Executes commands in sub-processes
symfony/service-contracts     v2.5.0 ~ v3.0.0 Generic abstractions related to writing services
symfony/string                v5.4.2 ~ v6.0.2 Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/var-dumper            v5.4.2 ~ v6.0.2 Provides mechanisms for walking through any arbitrary PHP variable</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 16
drwxr-xr-x   4 root  wheel   128 Oct 12 10:38 .
drwxr-xr-x  90 root  wheel  2880 Jan  6 17:32 ..
-rw-r--r--   1 root  wheel    80 Jun  3  2021 brew
-rw-r--r--   1 root  wheel    83 Jun  3  2021 valet</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 3.3.9-140-gd880fcc
ORIGIN: https://github.com/Homebrew/brew
HEAD: d880fcc92a9692707b43e93d8231dd9c038bd61c
Last commit: 7 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aee4becffc9c8d38c5eb73d325f3212024a67b0d
Core tap last commit: 87 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 11.0.0.33.17
Xcode: 12.4</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name       Status  User     File
dnsmasq    none root     
mailhog    none          
mysql      stopped cristian ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx      none root     
php        none root     
php@7.3    none          
php@7.4    none          
php@8.0    none root     
postgresql none cristian 
redis      none cristian 
tor        none</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.80
mailhog 1.0.0
mysql 8.0.25_1
nginx 1.17.7
openssl@1.1 1.1.1m
php 8.1.1 8.0.9 8.0.7
php@7.3 7.3.29_1
php@7.4 7.4.27 7.4.20 7.4.22
php@8.0 8.0.14</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>automake
cfitsio
dnsmasq
gdal
ghostscript
graphviz
hdf5
imagemagick
jansson
libdap
libgeotiff
libheif
libomp
librsvg
mailhog
minio/stable/mc
minio/stable/minio
mysql
netcdf
nghttp2
nginx
numpy
nvm
php@7.3
poppler
postgis
postgresql
proj
rbenv
tor</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
jakehilborn/jakehilborn
minio/stable
robsalasco/libpostal
shivammathur/php</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.0.14 (cli) (built: Dec 17 2021 22:29:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.14, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/8.0
Loaded Configuration File:         /usr/local/etc/php/8.0/php.ini
Scan for additional .ini files in: /usr/local/etc/php/8.0/conf.d
Additional .ini files parsed:      /usr/local/etc/php/8.0/conf.d/error_log.ini,
/usr/local/etc/php/8.0/conf.d/ext-opcache.ini,
/usr/local/etc/php/8.0/conf.d/ext-xdebug.ini,
/usr/local/etc/php/8.0/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.17.7</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.80.0
Age => 9
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin20.6.0
SSL Version => (SecureTransport) OpenSSL/1.1.1m
ZLib Version => 1.2.11
libSSH Version => libssh2/1.10.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.40</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>total 8
drwx------   3 cristian  staff    96 Feb  1  2021 .
drwxr-xr-x+ 88 cristian  staff  2816 Jan  6 17:36 ..
-rw-------   1 cristian  staff    55 Feb  1  2021 ngrok.yml</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.21.5 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.17.7 (25 files, 2.1MB) *
  Poured from bottle on 2020-01-16 at 22:09:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/nginx/bin/nginx -g daemon off;
==> Analytics
install: 29,446 (30 days), 116,038 (90 days), 495,242 (365 days)
install-on-request: 29,393 (30 days), 115,830 (90 days), 494,146 (365 days)
build-error: 5 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 8.1.1 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.0.7 (497 files, 77.8MB)
  Built from source
/usr/local/Cellar/php/8.0.9 (497 files, 77.8MB)
  Built from source
/usr/local/Cellar/php/8.1.1 (512 files, 80.0MB)
  Poured from bottle on 2022-01-06 at 16:59:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.1/

To restart php after an upgrade:
  brew services restart php
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 97,287 (30 days), 294,091 (90 days), 756,217 (365 days)
install-on-request: 77,574 (30 days), 241,509 (90 days), 695,436 (365 days)
build-error: 91 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@3: stable 3.0.1 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

==> Analytics
install: 102,891 (30 days), 273,406 (90 days), 320,391 (365 days)
install-on-request: 73,376 (30 days), 215,407 (90 days), 253,240 (365 days)
build-error: 4,656 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.1.1 (fpm-fcgi) (built: Dec 17 2021 23:50:01)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/8.0/php-fpm.conf --test</summary>
<pre>[06-Jan-2022 17:37:15] NOTICE: configuration file /usr/local/etc/php/8.0/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 cristian  staff   543 Jun 20  2021 homebrew.mxcl.mysql.plist
-rw-r--r--   1 cristian  staff   551 Jun 19  2021 homebrew.mxcl.mysql@5.7.plist
-rw-r--r--   1 cristian  staff   719 May 14  2021 homebrew.mxcl.postgresql.plist
-rw-r--r--   1 cristian  staff   823 Mar  3  2021 homebrew.mxcl.redis.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 Jan  6 17:29 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 Jan  6 17:35 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   577 Jan  6 17:35 homebrew.mxcl.php.plist
-rw-r--r--   1 root  admin   636 Feb 25  2021 homebrew.mxcl.php@7.2.plist
-rw-r--r--   1 root  admin   585 Jan  6 17:35 homebrew.mxcl.php@8.0.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Jan  1  2020 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 192.168.0.1
nameserver 0.0.0.0</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/usr/local/etc/nginx/valet/valet.conf\n---\n"; cat /usr/local/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/usr/local/etc/nginx/valet/valet.conf
---

3:    #listen VALET_LOOPBACK:80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---
</details>

PS. Thanks for all the work you guys put into Valet! It's an awesome tool!

**Comment by driesvints** [comment] 2022-01-07 14:29
Thank you @cristiancalara for reporting this. I, however, cannot reproduce this with the steps you provided. Since this isn't a blocking issue I'm going to close this. If anyone has an idea what's causing this, we'd appreciate PR's to fix it. I also suggest attempting a fresh install of Valet and re-installing the different PHP binaries to see if that helps your situation.

**Closed by driesvints** 2022-01-07 14:29 UTC

**Comment by cristiancalara** [comment] 2022-01-07 15:31
Hey @driesvints, thanks for the quick reply :)

I can open a pull request with the change I think is required if I was not supposed to comment again on a closed issue, but thought it might be worth explaining this in a more simplified way. I just wanted to see if my general assumptions below are wrong somehow or if maybe I'm missing something. l tried to provide a failing test (as per the contribution guidelines), but as the CLI responses are always mocked, wasn't sure how to do that.

-- Further explication

I tested on another MacBook & with a fresh install and managed to replicate it. Though I think that maybe all my details above made the issue a bit harder understand / replicate. I think it actually boils down to this:

`cli/Valet/Brew.php@getRunningServices` is running  `sudo -u cristian brew services list` i.e. as the user https://share.getcloudapp.com/RBuyXQp7 . This will mean that it does not return any of the actual services that are started by Valet, as Valet starts all the services using `sudo`. In order to return the running services, I think we should use `sudo brew services list`. A screenshot of the difference in the return commands https://share.getcloudapp.com/z8ukneKZ - as you can see only using `sudo` without the user will return the valet ran services.

PS. the code for this was added in https://github.com/laravel/valet/commit/25c4fab2b446cd6e9bc0a2f1f4f7dafa1f7e7905 - was not sure if I should tag to owner here.

**Comment by driesvints** [comment] 2022-01-07 15:33
@cristiancalara thanks for that. It's indeed probably best to send in a PR so Matt can review that. Feel free to attempt one without tests for now.

**Comment by cristiancalara** [comment] 2022-01-15 08:09
hey @driesvints - I've created a PR on this - not sure if I need to do anything else to get it reviewed?

not a push on the time, as it's totally understandable that this might take more time to get to, but just wanted to make sure that I don't need to somehow manually ping someone on the PR / so basically to make sure that I did everything I needed to do on my end.

**Comment by driesvints** [comment] 2022-01-17 07:46
Hey @cristiancalara, thanks for that. Matt is pretty busy but I'll try to see if I can get it to his attention 👍

**Comment by benjibee** [comment] 2022-02-08 08:46
I'm running into this same issue. @driesvints has this issue been fixed or is awaiting a PR? I'm a bit confused as it's been marked as closed but seems to be an outstanding bug.

**Comment by driesvints** [comment] 2022-02-08 08:49
@benjibee the pr was merged and released. Which version are you on?

**Comment by benjibee** [comment] 2022-02-08 08:54
@driesvints I got confused here while SSH'd into a machine using v2.18.6, I see the PR from v2.18.7 and have upgraded. Sorry for the mistake!

**Comment by vesper8** [comment] 2022-02-15 14:27
Same issue here
