### ISSUE TITLE
`valet secure` doesnt add up TLD (.test)

### ISSUE THREAD

**Issue by m-bosch** [laravel/valet#1239] opened 2022-04-15 08:52 UTC
- Valet Version: 3.1.2
- PHP Version: 8.0 and 8.1

### Description:
After updating to 3.1.2 the method `valet secure doesnt add the TLD to the domain to secure.

`valet secured` gives the list of secured domains, in the list below you see the last one doesnt have the `.test` tld.

```
+---------------------------------------+
| Site                                  |
+---------------------------------------+
| test-site1.test            |
| test-site2.test                 |
| test-site-valet-3-1-2           |
+---------------------------------------+
```

### Steps To Reproduce:

- `composer global update`
- `valet -v`
- check if `3.1.2`
- go to project
- use `valet secure`
- check list with `valet secured`
- this project wont have the TLD in it to secure.

project in browser wont be secured with https.

**Comment by driesvints** [comment] 2022-04-15 08:58
In which version did it work for you?

**Comment by m-bosch** [comment] 2022-04-15 08:59
Hi @driesvints, when i returned to version 3.1.1, it works again so it should be something in the update of yesterday 3.1.2?

**Comment by driesvints** [comment] 2022-04-15 09:19
I suspect https://github.com/laravel/valet/pull/1088 will be the culprit her. @antonioribeiro do you have any ideas?

**Comment by mattstauffer** [comment] 2022-04-15 15:49
I tested this exact issue before merging the pull request, and couldn't reproduce it, but now that it's released, I can. 🤦🏻‍♂️

<img width="585" alt="image" src="https://user-images.githubusercontent.com/151829/163591967-a772cb0a-e8e9-4f35-b99a-108f70d87426.png">

I'm going to roll back `3.1.2`. Sorry!

**Comment by mattstauffer** [comment] 2022-04-15 15:53
Fixed in https://github.com/laravel/valet/releases/tag/v3.1.3

**Closed by mattstauffer** 2022-04-15 15:53 UTC
Labels: bug
